name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: ${{ matrix.os }} - ${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        include:
          - os: ubuntu-latest
            compiler: gcc

          - os: ubuntu-latest
            compiler: clang

          - os: windows-latest
            compiler: cl

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Configure CMake
        run: >
          cmake
          -S .
          -B build
          -DCMAKE_C_COMPILER=${{ matrix.compiler }}

      - name: Build
        run: cmake --build build --config Release

      - name: Test
        working-directory: build
        run: ctest -C Release --output-on-failure
